spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT
    username: root
    password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    timeout: 0
    lettuce:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 8
        min-idle: 0
  application:
    name: Spring-boot-rabbitmq
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    #开启消息回调
    publisher-confirms: true
    #设定命名空间 不同命名空间的资源不可相互访问 采用默认值
    virtual-host: "/"
server:
  port: 8888
mybatis:
  mapper-locations: mapper/*.xml